#!/bin/bash

# A basic python development with pyright as the language server
# The installed python version can be adjusted in install_python.sh

FROM ubuntu:22.04

COPY scripts/update_apt_source.sh /scripts/update_apt_source.sh
RUN bash /scripts/update_apt_source.sh

COPY scripts/install_emacs.sh /scripts/install_emacs.sh
RUN bash /scripts/install_emacs.sh

COPY scripts/install_fonts.sh /scripts/install_fonts.sh
COPY downloads/FiraCode.tar.xz /scripts/FiraCode.tar.xz
COPY downloads/NerdFontsSymbolsOnly.tar.xz /scripts/NerdFontsSymbolsOnly.tar.xz
RUN bash /scripts/install_fonts.sh

COPY scripts/install_ssh_server.sh /scripts/install_ssh_server.sh
RUN bash /scripts/install_ssh_server.sh

COPY scripts/setup_time_zone.sh /scripts/setup_time_zone.sh
RUN bash /scripts/setup_time_zone.sh

COPY scripts/install_python.sh /scripts/install_python.sh
RUN bash /scripts/install_python.sh

ARG VERSION=v20.5.1
COPY downloads/node-$VERSION-linux-x64.tar.xz /scripts/node-$VERSION-linux-x64.tar.xz
COPY scripts/install_node.sh /scripts/install_node.sh
RUN bash /scripts/install_node.sh

# install necesary packages
RUN npm --registry https://registry.npmmirror.com install -g pyright
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple autopep8

EXPOSE 22

ENV TERM=xterm-256color
ENV LSP_USE_PLISTS=true

ENTRYPOINT service ssh restart && bash
