#!/bin/bash

# A basic python development with pyright as the language server
# The installed python version can be adjusted in install_python.sh

FROM ubuntu:22.04

COPY scripts/update_apt_source.sh /scripts/update_apt_source.sh
RUN bash /scripts/update_apt_source.sh

COPY scripts/install_ssh_server.sh /scripts/install_ssh_server.sh
RUN bash /scripts/install_ssh_server.sh

COPY scripts/setup_time_zone.sh /scripts/setup_time_zone.sh
RUN bash /scripts/setup_time_zone.sh

COPY scripts/install_python.sh /scripts/install_python.sh
RUN bash /scripts/install_python.sh

EXPOSE 22

ENV TERM=xterm-256color
ENV LSP_USE_PLISTS=true

ENTRYPOINT service ssh restart && bash
